Repository Book-Mile/backend, pull requests merged in 2025-01, with the labels that each got.

#48 [Refactor/#46] 전체적인 리팩토링
  src/main/java/com/bookmile/backend/domain/book/entity/Book.java
  src/main/java/com/bookmile/backend/domain/book/service/Impl/BookListServiceImpl.java
  src/main/java/com/bookmile/backend/domain/group/dto/req/GroupCreateRequestDto.java
  src/main/java/com/bookmile/backend/domain/group/dto/res/GroupCreateResponseDto.java
  src/main/java/com/bookmile/backend/domain/group/entity/Group.java
  src/main/java/com/bookmile/backend/domain/group/service/Impl/GroupServiceImpl.java
  src/main/java/com/bookmile/backend/domain/image/entity/Image.java
  src/main/java/com/bookmile/backend/domain/record/entity/Record.java
  src/main/java/com/bookmile/backend/domain/record/service/Impl/RecordServiceImpl.java
  src/main/java/com/bookmile/backend/domain/review/entity/Review.java
  src/main/java/com/bookmile/backend/domain/review/service/Impl/ReviewServiceImpl.java
  src/main/java/com/bookmile/backend/domain/template/entity/Template.java
Labels: 리팩토링, 이슈해결

#51 [Refactor/#47] dto 변환 로직 및 유효성 검사 리펙토링, 그룹 상태에 따른 조회 기능 3개로 분리 및 공개/비공개 설정 추가
  src/main/java/com/bookmile/backend/domain/group/controller/GroupController.java
  src/main/java/com/bookmile/backend/domain/group/dto/req/GroupPrivateRequestDto.java
  src/main/java/com/bookmile/backend/domain/group/dto/req/GroupSearchRequestDto.java
  src/main/java/com/bookmile/backend/domain/group/dto/req/GroupStatusUpdateRequestDto.java
  src/main/java/com/bookmile/backend/domain/group/dto/res/GroupCreateResponseDto.java
  src/main/java/com/bookmile/backend/domain/group/dto/res/GroupDetailResponseDto.java
  src/main/java/com/bookmile/backend/domain/group/dto/res/GroupJoinResponseDto.java
  src/main/java/com/bookmile/backend/domain/group/dto/res/GroupListResponseDto.java
  src/main/java/com/bookmile/backend/domain/group/dto/res/GroupMemberResponseDto.java
  src/main/java/com/bookmile/backend/domain/group/dto/res/GroupStatusUpdateResponseDto.java
  src/main/java/com/bookmile/backend/domain/group/entity/Group.java
  src/main/java/com/bookmile/backend/domain/group/repository/GroupRepository.java
  src/main/java/com/bookmile/backend/domain/group/service/GroupJoinService.java
  src/main/java/com/bookmile/backend/domain/group/service/GroupService.java
  src/main/java/com/bookmile/backend/domain/group/service/Impl/GroupJoinServiceImpl.java
  src/main/java/com/bookmile/backend/domain/group/service/Impl/GroupMemberServiceImpl.java
  src/main/java/com/bookmile/backend/domain/group/service/Impl/GroupServiceImpl.java
  src/main/java/com/bookmile/backend/domain/template/dto/res/TemplateResponseDto.java
  src/main/java/com/bookmile/backend/domain/userGroup/repository/UserGroupRepository.java
  src/main/java/com/bookmile/backend/global/common/StatusCode.java
Labels: 기능구현, 리팩토링, 문서화, 이슈해결

#59 Feat : 마이페이지 유저가 참여한 그룹 기록 조회 구현
  src/main/java/com/bookmile/backend/domain/userGroup/controller/UserGroupController.java
  src/main/java/com/bookmile/backend/domain/userGroup/dto/req/UserGroupSearchRequestDto.java
  src/main/java/com/bookmile/backend/domain/userGroup/dto/res/UserGroupSearchResponseDto.java
  src/main/java/com/bookmile/backend/domain/userGroup/repository/UserGroupRepository.java
  src/main/java/com/bookmile/backend/domain/userGroup/service/Impl/UserGroupServiceImpl.java
  src/main/java/com/bookmile/backend/domain/userGroup/service/UserGroupService.java
Labels: 기능구현

#62 [Feat/#56] 소셜 연동 해제기능 ( + 추가 엔티티 생성)
  src/main/java/com/bookmile/backend/domain/record/controller/RecordController.java
  src/main/java/com/bookmile/backend/domain/user/controller/OAuthController.java
  src/main/java/com/bookmile/backend/domain/user/controller/UserController.java
  src/main/java/com/bookmile/backend/domain/user/entity/User.java
  src/main/java/com/bookmile/backend/domain/user/entity/UserOAuth.java
  src/main/java/com/bookmile/backend/domain/user/repository/UserOAuthRepository.java
  src/main/java/com/bookmile/backend/domain/user/repository/UserRepository.java
  src/main/java/com/bookmile/backend/domain/user/service/OAuthService.java
  src/main/java/com/bookmile/backend/domain/user/service/UserService.java
  src/main/java/com/bookmile/backend/domain/user/service/impl/OAuthServiceImpl.java
  src/main/java/com/bookmile/backend/domain/user/service/impl/UserServiceImpl.java
  src/main/java/com/bookmile/backend/global/common/RandomNickname.java
  src/main/java/com/bookmile/backend/global/common/StatusCode.java
  src/main/java/com/bookmile/backend/global/oauth/CustomOAuth2UserService.java
  src/main/java/com/bookmile/backend/global/oauth/OAuth2SuccessHandler.java
  src/main/java/com/bookmile/backend/global/oauth/OAuth2UnlinkService.java
  src/main/java/com/bookmile/backend/global/oauth/OAuth2UserInfo.java
  src/test/java/com/bookmile/backend/domain/user/service/UserServiceImplTest.java
Labels: 기능구현, 리팩토링
